name: Deploy

on:
  push:
  workflow_dispatch:

permissions:
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Check out repository
        uses: actions/checkout@v4

      - name: Fetch wheels
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          mkdir -p page/static

          MLIR_PYTHON_WHEEL_NAME=$(gh release view mlir-python-bindings --repo llvm/eudsl --json 'assets' -q '[.assets[] | select(.name | contains("cp312-pyodide")) | .name] | last')
          MLIR_PYTHON_WHEEL_URL=$(gh release view mlir-python-bindings --repo llvm/eudsl --json 'assets' -q '[.assets[] | select(.name | contains("cp312-pyodide")) | .url] | last')
          echo "Downloading ${MLIR_PYTHON_WHEEL_NAME} from ${MLIR_PYTHON_WHEEL_URL}"
          wget -O page/static/${MLIR_PYTHON_WHEEL_NAME} "${MLIR_PYTHON_WHEEL_URL}"
          echo "MLIR_PYTHON_WHEEL_NAME=$MLIR_PYTHON_WHEEL_NAME" >> $GITHUB_ENV
          echo "MLIR_PYTHON_WHEEL_URL=$MLIR_PYTHON_WHEEL_URL" >> $GITHUB_ENV

          EUDSL_PYTHON_EXTRAS_NAME=$(gh release view eudsl-python-extras --repo llvm/eudsl --json 'assets' -q '.assets | last | .name')
          EUDSL_PYTHON_EXTRAS_URL=$(gh release view eudsl-python-extras --repo llvm/eudsl --json 'assets' -q '.assets | last | .url')
          echo "Downloading ${EUDSL_PYTHON_EXTRAS_NAME} from ${EUDSL_PYTHON_EXTRAS_URL}"
          wget -O page/static/${EUDSL_PYTHON_EXTRAS_NAME} "${EUDSL_PYTHON_EXTRAS_URL}"
          echo "EUDSL_PYTHON_EXTRAS_NAME=$EUDSL_PYTHON_EXTRAS_NAME" >> $GITHUB_ENV
          echo "EUDSL_PYTHON_EXTRAS_URL=$EUDSL_PYTHON_EXTRAS_URL" >> $GITHUB_ENV
  
      - name: Create WASM console page
        run: |
          mkdir -p page/console

          cp index.template.html page/console/index.html
          sed -i 's/{{PYODIDE_VERSION}}/v0.27.7/g' page/console/index.html
          sed -i "s#{{MLIR_PYTHON_WHEEL_PATH}}#../static/${MLIR_PYTHON_WHEEL_NAME}#g" page/console/index.html
          sed -i "s#{{EUDSL_PYTHON_EXTRAS_PATH}}#../static/${EUDSL_PYTHON_EXTRAS_NAME}#g" page/console/index.html

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install the dependencies
        run: |
          python -m pip install -r requirements.txt

      - name: Create WASM jupyterlite page
        run: |
          mkdir -p page/jupyter

          jupyter lite build --output-dir page/jupyter --piplite-wheels ./page/static/$MLIR_PYTHON_WHEEL_NAME --piplite-wheels ./page/static/$EUDSL_PYTHON_EXTRAS_NAME

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: page
  
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
